# Generated by Django 5.0.3 on 2024-04-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_certificates_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='image',
        ),
    ]
