# Generated by Django 5.0.3 on 2024-04-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_certificates_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
